#!/bin/bash

if [ $(whoami) != 'root' ]; then
    echo "Must be root to run $0"
    exit 1;
fi

#-------------------------------------------------------------
# List of all library files to setup an
# environment.
#      PKGS[*],  PKGS[@] refers to all elements of the array
#      #PKGS[*], #PKGS[@] refers to the length of the array
#-------------------------------------------------------------
PKGS=(libboost-all-dev
      git-all
      gitk
      gcc-arm-linux-gnueabi
      vim)
TOT_PKGS=${#PKGS[@]}
FAIL_PKGS=()

echo "Installing Libraries total: ${TOT_PKGS} process: $$"

for index in ${!PKGS[*]}; do
    echo "Installing package ${index}/${TOT_PKGS}: ${PKGS[$index]}"
    apt-get install ${PKGS[$index]}
    if [ $RESULT != 0 ]; then
        FAIL_PKGS+=${PKGS[$index]}
    fi
done

if [ ${#FAIL_PKGS[*]} != 0 ]; then
    echo "Following Pacakages failed to install: ${FAIL_PKGS} "
fi

# Need to add ppa
# sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
# sudo apt-get update
# sudo apt-get install-gcc-arm-embedded


exit 0
