#!/bin/bash

UTILS_PATH=~/bin_repo/conf_files

ln -s $UTILS_PATH/bashrc ~/.bashrc
ln -s $UTILS_PATH/bash_aliases ~/.bash_aliases
ln -s $UTILS_PATH/bash_profile ~/.bash_profile
ln -s $UTILS_PATH/vimrc ~/.vimrc

